### ISSUE TITLE
README.md -- Anyone can work for this Project .readme file -- Need a attractive one

### ISSUE THREAD

**Issue by sanchit2107** [sanchit2107/Flight-Management-System#29]
### What to contribute--
_**Any beginner who wants to create their first PR. they can work on README.md file for this project. And design the same according to Full-stack Project with Flight Management theme**_

Need to focus on:

- Simple and attractive
- Must have a theme of Flight Management System
- Looks like the Full-stack Project README.md

**Comment by ancasimon** [comment]
Hi Sanchit - is there a specific Readme.md you have in mind when you say it should look like the Full-stack Project README.md? If you can share an example of a Readme file this one should resemble in terms of structure and layout, that would be great. Tia!

**Comment by sanchit2107** [comment]
Hello Tia!!

**What you can do is like:** 

_You can use some interactive(may use HTML for creating the same) and few guidelines for creating the README.md file which contains the Project Description such as_

- Add Title of the Project
- Description of Project(Describe by words and images alike)
- Technologies Used
- Technical Description of this project like- Installation, Setup, etc.
- Use code formating
- Must have structure as similar to other README.md only(like simple, interactive, and most important it should be informative)

_Note:_ @ancasimon as I discussed looks-wise Full-stack it simply means it should have information, images, or gifs which indicates this project is based on Full-stack technologies such as Angular, Spring Boot, and many more. 
- For that, you can simply add images of technologies used
- May add information that helps the developers to find all information about the project.

I hope now you get it and looking for your PR in this awesome project.

P.S.: If you need any more information about the project or any technologies or constraints used in this project then please let me know I will describe in detail.

**Comment by sanchit2107** [comment]
@ancasimon are you still interested in this?

If yes then please let me know I will assign this to you.

**Comment by ancasimon** [comment]
Yes, please! I would like to! I don't have experience with Angular or SpringBot - but I love to learn and I like some good clear Readmes, so I would love to work on this as much as I can! - If that's ok with you!

Should I clone down the project and run `ng serve` to run it?

**Comment by sanchit2107** [comment]
@ancasimon You can proceed with your work. I'm okay with the same.

Yes, you can fork this repo and then clone. After that, you can use **ng serve** to run it.

Waiting to see your PR here.

**Comment by ancasimon** [comment]
@sanchit2107 Hi Sanchit - I am running into an issue when I try to run the project - see screenshot below. 
I tried some of the recommendations on this stackoverflow issue: https://stackoverflow.com/questions/53096996/angular-cli-error-the-serve-command-requires-to-be-run-in-an-angular-project-b 

But I am still stuck - do you have any ideas I could try, please ? Thanks!
Anca

PS It looks like I could go here and try to figure out a solution too but I am not sure I know the answers to all the questions there: https://update.angular.io/

<img width="1085" alt="Angular_error" src="https://user-images.githubusercontent.com/59633395/96672607-4c06cb80-132a-11eb-9324-f297c637d7fe.png">

**Comment by ancasimon** [comment]
And a couple more questions please:
1 - Header and footer say "Flight Reservation System" but other places say "Flight Management System" - it might be best to use the same app name throughout the app - so Flight Reservation System or Flight Management System. [Or maybe something catchier like: FlySmart, Volare (To fly in Latin), SkyMaster ...] "Flight Reservation System" seems more accurate since the app seems to be about reservations - not so much managing the flights from a control tower's staff perspective (which was my first thought after seeing "Flight Management"). Any option is fine - but consistency is always good!

**Comment by sanchit2107** [comment]
> @sanchit2107 Hi Sanchit - I am running into an issue when I try to run the project - see screenshot below.
> I tried some of the recommendations on this stackoverflow issue: https://stackoverflow.com/questions/53096996/angular-cli-error-the-serve-command-requires-to-be-run-in-an-angular-project-b
> 
> But I am still stuck - do you have any ideas I could try, please ? Thanks!
> Anca
> 
> PS It looks like I could go here and try to figure out a solution too but I am not sure I know the answers to all the questions there: https://update.angular.io/
> 
> <img alt="Angular_error" width="1085" src="https://user-images.githubusercontent.com/59633395/96672607-4c06cb80-132a-11eb-9324-f297c637d7fe.png">

**Have you tried the following steps:**

1. First, install angular CLI in your system
2. Then clone this project
3. And run npm install in cmd line in the directory of the project
4. Then after running ng serve command

If still getting an error then please let me know.

**Comment by sanchit2107** [comment]
> And a couple more questions please:
> 
> 1. Header and footer say "Flight Reservation System" but other places say "Flight Management System" - it might be best to use the same app name throughout the app - so Flight Reservation System or Flight Management System. [Or maybe something catchier like: FlySmart, Volare (To fly in Latin), SkyMaster ...] "Flight Reservation System" seems more accurate since the app seems to be about reservations - not so much managing the flights from a control tower's staff perspective (which was my first thought after seeing "Flight Management"). Any option is fine - but consistency is always good!
> 2. What got the team interested in working on this idea / project? Do you all like to travel? Any favorite places you like to travel to? Anything like that :) No worries if the answer is no - we just happened to work on it :) - sometimes it's fun to include a background/personal info in the Readme so that's why I asked.
> 3. Do you think you there will be more opportunities for contributions from other developers in the future? If yes - we could add a How to Contribute section like they did here with Want to Contribute?: https://github.com/sprakash57/shortify
> 4. And yes, please - any details you can provide about the project / technologies / constraints would be great!!
> 5. I started a draft in the `ars-ReadMeUpdates` branch - just fyi. I pushed it just so you can look at it if you want and let me know if I am on the right track! Thanks - you can find it here: https://github.com/ancasimon/Flight-Management-System/tree/ars-ReadmeUpdates

**_I am very happy to see that you go through the complete project and find out these issues in front and absolutely we need to work on that._**

Now the answers to your questions are here:

1. We can keep the name of the system as the Flight Reservation System.
2. Yaa you can say that I like to travel and explore new places. And also booking on your own by just clicking on the screen makes the task easy.
3. Ya sure we can add the same that is want to contribute section here itself. It will be a good option for this one.
4. **Ya sure I am adding the details regarding all mentioned below in the next comment:**
5. Yes you are doing great. Just need to work on Presentation skills.

Thanks
Great Going..

**Comment by sanchit2107** [comment]
### About Flight Reservation System:
The Flight Reservation System is a Java-based booking solution for flight tickets. It consolidates data provided by different airline carriers and hence provides the user details and rates in real-time. Travellers may want to make changes in their bookings. The
application allows them to book, cancel, view and update their bookings with ease. Other than this, it eases the management of bookings too. All the bookings, flights, schedules and routes can be viewed, added and modified on a single application by the administrator.

### Constraints used:
**_Inscope:_**
Following is the functionality provided by the system:
There are two categories of people who would access the system: customer and
administrator. Each of these would have some exclusive privileges.
1. The customer can:
a. Create his user account.
b. Login into the application.
c. Check for available flights.
d. Make a booking.
e. View the bookings made.
f. Cancel or modify a booking.
2. The administrator can:
a. Login into the application.
b. Add flight, schedule and route details.
c. View the flight, schedule and route details.
d. Cancel or modify the flight, schedule and route details.

**_Outscope:_**
The following functionalities have not been covered under the application:
1. The application does not cover boarding pass generation and seating plans.
2. Third party applications like email & sms integrations.
3. Payments are not yet accepted by the application.

### Technologies used:
_**Backend**_
1. Java 8
2. Spring Boot
3. JPA
4. REST API
5. JUnit Testing

**_Frontend_**
1. HTML
2. CSS
3. Bootstrap
4. Typescript
5. Angular

**_Database:_**

1. Oracle or
2. H2 Database

@ancasimon For any more details please let me know.

Soon to see your first PR here.

**Comment by ancasimon** [comment]
> > @sanchit2107 Hi Sanchit - I am running into an issue when I try to run the project - see screenshot below.
> > I tried some of the recommendations on this stackoverflow issue: https://stackoverflow.com/questions/53096996/angular-cli-error-the-serve-command-requires-to-be-run-in-an-angular-project-b
> > But I am still stuck - do you have any ideas I could try, please ? Thanks!
> > Anca
> > PS It looks like I could go here and try to figure out a solution too but I am not sure I know the answers to all the questions there: https://update.angular.io/
> > <img alt="Angular_error" width="1085" src="https://user-images.githubusercontent.com/59633395/96672607-4c06cb80-132a-11eb-9324-f297c637d7fe.png">
> 
> **Have you tried the following steps:**
> 
> 1. First, install angular CLI in your system
> 2. Then clone this project
> 3. And run npm install in cmd line in the directory of the project
> 4. Then after running ng serve command
> 
> If still getting an error then please let me know.


Hi Sanchit! @sanchit2107 
Still getting the same issue!  :( I did what you said and created a new clone but the same error still comes up.... Any other ideas?

<img width="858" alt="Screen Shot 2020-10-23 at 7 43 07 PM" src="https://user-images.githubusercontent.com/59633395/97063923-2ff06d80-1568-11eb-8fd8-a049fa194710.png">

**Comment by ancasimon** [comment]
@sanchit2107 
One more question please: Would you consider the Outscope to be future features / backlog? Or are those features you may not be necessarily planning to include at all in the future?

**Comment by ancasimon** [comment]
Raised a PR for you, Sanchit. Please let me know of any changes you would like to see! Also - see my comments in the PR regarding the changes. Thanks!
PR: https://github.com/sanchit2107/Flight-Management-System/pull/30
@sanchit2107

**Comment by sanchit2107** [comment]
> @sanchit2107
> One more question please: Would you consider the Outscope to be future features / backlog? Or are those features you may not be necessarily planning to include at all in the future?

**_Yes for sure we can add this into the future features or backlog_**

**Comment by sanchit2107** [comment]
> > > @sanchit2107 Hi Sanchit - I am running into an issue when I try to run the project - see screenshot below.
> > > I tried some of the recommendations on this stackoverflow issue: https://stackoverflow.com/questions/53096996/angular-cli-error-the-serve-command-requires-to-be-run-in-an-angular-project-b
> > > But I am still stuck - do you have any ideas I could try, please ? Thanks!
> > > Anca
> > > PS It looks like I could go here and try to figure out a solution too but I am not sure I know the answers to all the questions there: https://update.angular.io/
> > > <img alt="Angular_error" width="1085" src="https://user-images.githubusercontent.com/59633395/96672607-4c06cb80-132a-11eb-9324-f297c637d7fe.png">
> > 
> > 
> > **Have you tried the following steps:**
> > 
> > 1. First, install angular CLI in your system
> > 2. Then clone this project
> > 3. And run npm install in cmd line in the directory of the project
> > 4. Then after running ng serve command
> > 
> > If still getting an error then please let me know.
> 
> Hi Sanchit! @sanchit2107
> Still getting the same issue! :( I did what you said and created a new clone but the same error still comes up.... Any other ideas? NOTE: I am working on a Mac computer - could that be an issue??....
> 
> <img alt="Screen Shot 2020-10-23 at 7 43 07 PM" width="858" src="https://user-images.githubusercontent.com/59633395/97063923-2ff06d80-1568-11eb-8fd8-a049fa194710.png">

**In reference to your error, please follow the following steps:**
1. Kindly check whether you had installed the angular in your machine or not by entering the command `ng --version`. If you have angular installed on your machine then you will get any message where Angular CLI is written in very large font along with the version you have as mentioned in the image attached below.
![image](https://user-images.githubusercontent.com/44783353/97070206-2a406980-15f4-11eb-935d-d3c191a88539.png)

if you don't get the same message as attached in the image, then you need to install Angu;ar CLI first.

I hope this will solve your issue. If not then please let me know again.

And thanks for your @ancasimon PR here!!


Regards
Sanchit Singhal
