### ISSUE TITLE
App name inconsistent

### ISSUE THREAD

**Issue by ancasimon** [sanchit2107/Flight-Management-System#33]
Sometimes, it says Flight Management System; other times, Flight Reservation System. 

Per Sanchit, we decided to keep it as Flight Reservation System.

**Comment by ancasimon** [comment]
New PR for you, @sanchit2107  making these changes: https://github.com/sanchit2107/Flight-Management-System/pull/32

Thanks!

**Comment by sanchit2107** [comment]
Okay @ancasimon 

Thanks for letting me know I will update this asap.
